// Code generated by MockGen. DO NOT EDIT.
// Source: ingestion.go
//
// Generated by this command:
//
//	mockgen -source=ingestion.go -destination=mock_ingestion.go -package=ports
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	domain "log-guardian/internal/core/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInputProvider is a mock of InputProvider interface.
type MockInputProvider struct {
	ctrl     *gomock.Controller
	recorder *MockInputProviderMockRecorder
	isgomock struct{}
}

// MockInputProviderMockRecorder is the mock recorder for MockInputProvider.
type MockInputProviderMockRecorder struct {
	mock *MockInputProvider
}

// NewMockInputProvider creates a new mock instance.
func NewMockInputProvider(ctrl *gomock.Controller) *MockInputProvider {
	mock := &MockInputProvider{ctrl: ctrl}
	mock.recorder = &MockInputProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputProvider) EXPECT() *MockInputProviderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockInputProvider) Read(ctx context.Context, output chan<- domain.LogEvent, errChan chan<- error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Read", ctx, output, errChan)
}

// Read indicates an expected call of Read.
func (mr *MockInputProviderMockRecorder) Read(ctx, output, errChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockInputProvider)(nil).Read), ctx, output, errChan)
}
