// Code generated by MockGen. DO NOT EDIT.
// Source: id_generator.go
//
// Generated by this command:
//
//	mockgen -source=id_generator.go -destination=mock_id_generator.go -package=ports
//

// Package ports is a generated GoMock package.
package ports
